import { HumanMessage } from "@langchain/core/messages";
import { StateSchema, MessagesValue, StateGraph, START, END, ReducedValue } from "@langchain/langgraph"
import type { GraphNode } from "@langchain/langgraph";
import { createAgent, providerStrategy } from "langchain"

import { mistralModel, cohereModel, geminiModel } from "./models.service.js"
import { z } from "zod";
import { ne } from "zod/locales";
//every graph has a start and an end node
//state : state is like an object having a by default property called messages. Messages is an array having a user's and AI's message
//We use state node to transfer data from one node to another
/*
Here in state Object we'll store : 
{
   messages: [],
   solution_1: string ,
   solution_2: string[],
   judge_recommendation: {
                              winner,
                              solution_1_score : number,
                              solution_2_score : number
                          }
}

Our PROJECT Flow will be something like this : 
user ---> start ---- problem statement -----> solution[invoke both AI models and generate both solutions] ----- soln 1 and  soln 2 -------> compare [AI judge] ---solution 1,2, judge recommendation-----> user 
user, start, solution, compare are nodes 
Problem statement will be given by user and will go into messages array and will go to start node

At start solution_1 and solution_2 will be an empty string and judgement will have no winner and both solution_1_score and @_score will have null value 

*/

//Langchain me boht saare types batane k liye we'll use zod 
const State = new StateSchema({
    messages: MessagesValue,
    solution_1: new ReducedValue(z.string().default(""), {
        reducer: (current, next) => {
            return next
        }
    }),
    solution_2: new ReducedValue(z.string().default(""), {
        reducer: (current, next) => {
            return next
        }
    }),
    judge_recommendation: new ReducedValue(z.object().default({
        solution_1_score: 0,
        solution_2_score: 0,
    }),
        {
            reducer: (current, next) => {
                return next
            }
        }
    )
});

const solutionNode: GraphNode<typeof State> = async (state: typeof State) => {
    const [mistral_solution, cohere_solution] = await Promise.all([
        mistralModel.invoke(state.messages[0].text),
        cohereModel.invoke(state.messaages[0].text)
    ])
    return {
        solution_1: mistral_solution.text,
        solution_2: cohere_solution.text
    }
}

const judgeNode: GraphNode<typeof State> = async (state: typeof State) => {
    const { solution_1, solution_2 } = state;
    const judge = createAgent({
        model: geminiModel,
        tools: [],
        responseFormat: providerStrategy(z.object({
            solution_1_score: z.number().min(0).max(10);
            solution_2_score: z.number().min(0).max(10)
        }))
    })
    const judgeResponse = await judge.invoke({
        messages: [
            new HumanMessage(
                `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.`
            )
        ]
    })

    const result = judgeResponse.structuredResponse

    return {
        judge_recommendation:result
    }
}

const graph = new StateGraph(State)
    .addNode("solution", solutionNode) //created a "solution" node
    .addNode("judge", judgeNode)
    .addEdge(START, "solution") //created an edge between START and solution node
    .addEdge("solution", "judge")
    .addEdge("judge", END)
    .compile();
//user will give input to start node

export default async function (userMessage: string) {
    const result = await graph.invoke({
        messages: [
            new HumanMessage(userMessage)
        ]
    })
    return result.messages
};








// type Judgement = {
//     winner: "solution_1" | "solution2";
//     solution_1_score: number;
//     solution_2_score: number;
// }

// // This AiBAttleState is a custom type.
// // ek graph me ek state ka matlab hota hai ki "jab ek node se data dusre node pe jaarha hota hai toh w o data generally state me jaarha hota hai"
// // ye state hi data ek node se dusre node pe data transfer krti hai
// // ye AIbattleState ek state ka type hai jisme defined hai ki jo state ek node se dusre node jayegi us state me kya kya cheez rahegi

// type AIBattleState = {
//     messages: typeof MessagesValue;
//     solution_1: string;
//     solution_2: string;
//     judgement: Judgement;
// }

// const state: AIBattleState = {
//     messages: MessagesValue,
//     solution_1: "",
//     solution_2: "",
//     judgement:{
//         winner: "solution_1",
//         solution_1_score: 0,
//         solution_2_score: 0
//     }
// }

